# escape=`
ARG JAVA_VERSION=17.0.6_10
ARG JAVA11_IMAGE_VERSION=3107.v665000b_51092-5

FROM eclipse-temurin:${JAVA_VERSION}-jdk-windowsservercore-1809 AS core
# Use inbound-agent's JDK11 only for running jenkins agent, not as default java
FROM jenkins/inbound-agent:"${JAVA11_IMAGE_VERSION}"-jdk11-nanoserver-1809

# ProgressPreference => Disable Progress bar for faster downloads
SHELL ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Adding jdk17 from eclipse-temurin
# Use ENV and not ARG : https://docs.docker.com/engine/reference/builder/#using-arg-variables
ENV JAVA_HOME=C:/tools/jdk-17
COPY --from=core C:/openjdk-17 "${JAVA_HOME}"

# https://github.com/StefanScherer/dockerfiles-windows/tree/master/golang-issue-21867
COPY --from=core C:/windows/system32/netapi32.dll C:/windows/system32/netapi32.dll

ARG MAVEN_VERSION=3.9.1
RUN Invoke-WebRequest -Uri "https://archive.apache.org/dist/maven/maven-3/${env:MAVEN_VERSION}/binaries/apache-maven-${env:MAVEN_VERSION}-bin.zip" -OutFile ${env:TEMP}/apache-maven.zip ; `
  Expand-Archive -Path "${env:TEMP}/apache-maven.zip -Destination" C:/tools ; `
  Remove-Item ${env:TEMP}/apache-maven.zip ;

# Installation of Launchable globally (no other python tool)
ARG PYTHON_VERSION=3.11.3
ARG LAUNCHABLE_VERSION=1.63.0



# https://community.chocolatey.org/install.ps1
COPY .\installChocolatey.ps1 "${env:TEMP}/installChocolatey.ps1"
RUN "${env:TEMP}/installChocolatey.ps1"
# hadolint ignore=DL3059
RUN Remove-Item "${env:TEMP}/installChocolatey.ps1";

# hadolint ignore=DL3059
RUN dir "${env:ProgramFiles}"
# hadolint ignore=DL3059
RUN dir "C:/"
# hadolint ignore=DL3059
RUN dir "C:/${env:ProgramData}/Chocolatey/"
# hadolint ignore=DL3059
RUN Start-Process -FilePath "C:/${env:ProgramData}/Chocolatey/bin/choco.exe" -ArgumentList "install","python3","--yes","--no-progress","--limit-output","--fail-on-error-output","--version","${env:PYTHON3_VERSION}"
# hadolint ignore=DL3059
RUN dir "C:/"


# # hadolint ignore=DL3059
# RUN Invoke-WebRequest -Uri "https://www.python.org/ftp/python/${env:PYTHON_VERSION}/python-${env:PYTHON_VERSION}-amd64.exe" -OutFile "${env:TEMP}/install-python.exe";
# # hadolint ignore=DL3059
# # RUN "C:/tmp/install-python.exe" /quiet;
# # # RUN "C:/tmp/install-python.exe" /quiet InstallAllUsers=1 PrependPath=1;
# # # hadolint ignore=DL3059
# # RUN Remove-Item "C:/tmp/" -Recurse;
# # # hadolint ignore=DL3059
# # RUN Move-Item -Path "C:/Program File/Python311/" -Destination "C:/tools/";
# # # hadolint ignore=DL3059
# # RUN "C:/tools/Python311/python.exe" -m pip install --no-cache-dir --upgrade setuptools wheel pip;
# # # hadolint ignore=DL3059
# # RUN "C:/tools/Python311/python.exe" -m pip install --no-cache-dir launchable=="${env:LAUNCHABLE_VERSION}";
# # hadolint ignore=DL3059
# RUN Start-Process -FilePath "${env:TEMP}/install-python.exe" -ArgumentList "/quiet","InstallAllUsers=1","PrependPath=1","Install_test=0";
# #& "C:/tmp/install-python.exe" /quiet InstallAllUsers=1 PrependPath=1;
# # hadolint ignore=DL3059
# RUN Start-Sleep -Seconds 45 
# # hadolint ignore=DL3059
# RUN Remove-Item "${env:TEMP}/install-python.exe";
# # hadolint ignore=DL3059
# RUN dir "${env:ProgramFiles}"
# # hadolint ignore=DL3059
# RUN dir C:/tools
# # hadolint ignore=DL3059
# RUN Move-Item -Path "${env:ProgramFiles}/Python311/" -Destination "C:/tools/python";
# # hadolint ignore=DL3059
# RUN Start-Process -FilePath "C:/tools/python/python.exe" -ArgumentList "--version";
# # hadolint ignore=DL3059
# RUN Start-Process -FilePath "C:/tools/python/python.exe" -ArgumentList "-m","pip","install","--no-cache-dir","--upgrade","setuptools","wheel","pip";
# # hadolint ignore=DL3059
# RUN Start-Process -FilePath "C:/tools/python/python.exe" -ArgumentList "-m","pip","install","--no-cache-dir","launchable==${env:LAUNCHABLE_VERSION}";

ENV MAVEN_HOME "C:/tools/apache-maven-${MAVEN_VERSION}"
ENV PATH="${JAVA_HOME}/bin;${PATH};${MAVEN_HOME}/bin;C:/tools/python/Scripts/"
